[template]
src = "core_site.tmpl"
dest = "/etc/hadoop/conf/core-site.xml"
keys = [
  "/aws_key",
  "/aws_secret_key"
]
uid = 0
reload_cmd = "export AWS_ACCESS_KEY_ID={{getv \"/aws_key\"}} && export AWS_SECRET_ACCESS_KEY={{getv \"/aws_secret_key\"}}"
